on: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
  
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: aks
        resource-group: aks-demos

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/azure-vote.yaml
